# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: På Tråden
email: pa.traden@knightec.se
description: >- # this means to ignore newlines until "baseurl:"
  I På Tråden diskuterar Peter van der Meulen och Jeger Ibrahim varanan vecka
  deras erfarenheter och utmaningar inom Java, Ruby, JavaScript, Rust,
  MySql, Postgres eller vad som dyker upp på tråden ;).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patraden.knightec.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DewirePaTraden
github_username:  pa-Traden
instagram_username: pa.traden
audio_domain: https://pa-traden-files.ams3.digitaloceanspaces.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

gems:
  - jekyll-paginate-v2

sass:
  sass_dir: _sass
  style: compressed

pagination:
  enabled: true
  per_page: 5

users:
- id: 1
  active: true
  first_name: Peter
  last_name: van der Meulen
  image_name: peter.jpg
  link: https://hendrikpeter.net
- id: 2
  active: true
  first_name: Jeger
  last_name: Ibrahim
  image_name: jeger.jpg


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
